apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${imageName}
  name: ${imageName}
  labels:
    app: ${imageName}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${imageName}
  template:
    metadata:
      labels:
        app: ${imageName}
    spec:      
      containers:
        - name: ${imageName}
          image: ${containerUrl}
          resources:
            limits:
              cpu: "1"
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 128Mi
          ports:
          - containerPort: 80